# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Full Height Hero
  description: Full height hero with text and images
  icon: 'chrome_reader_mode'
  tags:
    - Text
    - Image
    - Button
    - Flippable

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: ""
    subheading: ""
    buttons: 
      - text: ""
        link: ""
    features:
      image: 
        image_path: ""
        image_alt: ""
      feature:
        - heading: ""
          icon: ""
          text: ""
    background_image: ""
  style: 
    background_color: ""
  

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  feature:
    comment: "limit: 4 items"
  heading: 
    type: text 
  subheading: 
    type: textarea 
  icon: 
    type: image 
  text: 
    type: textarea
  background_image:
    type: image
  background_color:
    type: select 
    options:  
      values: 
        - id: "background-color: #ffffff; color: #222;"
          name: "Light"
        - id: "background-color: #000; color: #fff;"
          name: "Dark"
 